version: "3"

services:
  react: 
    container_name: react-ui
    build: ./client
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes: 
      - ./client:/usr/src/app
      - /client/node_modules
    ports: 
      - "3000:3000"
    stdin_open: true
    depends_on: 
      - node

  node:
    container_name: web-service
    restart: always
    build: ./server/
    environment:
     CHOKIDAR_USEPOLLING: "true"
    volumes: 
      - ./server:/usr/src/app
      - /server/node_modules
    ports:
      - '8080:3000'
    links:
      - db
    depends_on: 
      - db
  
  db:
    container_name: mongodb
    image: mongo:4.2
    ports:
      - '27017:27017' 
    volumes: 
      - ./server/mongo-volume:/data/db