services:
  client:
    build:
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
    stdin_open: true

  server:
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"

  proxy:
    container_name: proxy
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/:/etc/nginx/conf.d/
    depends_on:
      - client
      - server
