version: "3"

services:
  client:
    container_name: client
    build:
      context: ./client
    environment:
      EXPRESS_HOST: server
    volumes:
      - ./client:/usr/src/client
      - /client/node_modules

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/src/server
      - /server/node_modules
    env_file: ./server/.env
    environment:
      HOST: 0.0.0.0
      MONGO_HOST: mongo
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:4.2
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ./server/mongo-volume/:/data/db
      - ./.backups/mongodb/:/backups
