services:
  client:
    build:
      dockerfile: ./Dockerfile.prod
    ports:
      - "80:8080"
    environment:
      NODE_ENV: production
    depends_on:
      - server

  server:
    build:
      dockerfile: ./Dockerfile.prod
    environment:
      NODE_ENV: production
    volumes:
      - ./server:/usr/src/server
      - /server/node_modules
