version: "3"

services:
  client:
    build:
      context: ./client
    environment:
      EXPRESS_HOST: server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file: ./server/.env
    environment:
      HOST: 0.0.0.0
      MONGO_HOST: mongo
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ./server/mongo-volume/:/data/db
      - ./.backups/mongodb/:/backups
